package org.portfolio.userland.features.check.services;

import lombok.RequiredArgsConstructor;
import org.portfolio.userland.features.check.dto.CheckInfoResp;
import org.portfolio.userland.features.check.exceptions.CheckInterruptedException;
import org.portfolio.userland.system.base.BaseService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.info.BuildProperties;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.time.LocalDateTime;

/**
 * Service for check endpoints.
 */
@Service
@RequiredArgsConstructor
public class CheckService extends BaseService {
  private final ApplicationContext context;
  /** Build information of the application (generated by spring-boot-maven-plugin's build-info goal). */
  private final BuildProperties buildProperties;

  /** System name. */
  @Value("${app.main.name}")
  protected String systemName;

  /**
   * Resolve basic information about system.
   * @return Various basic information.
   */
  public CheckInfoResp info() {
    LocalDateTime bootAt = clockService.convert(context.getStartupDate());
    return CheckInfoResp.builder()
        .name(systemName)
        .nowAt(clockService.getNowUTC())
        .bootAt(bootAt)
        .version(buildProperties.getVersion())
        .profile(build)
        .build();
  }

  /**
   * Pretend to do some work.
   */
  public void pretendWork() {
    try {
      Thread.sleep(Duration.ofSeconds(30));
    } catch (InterruptedException ex) {
      // Restore the interrupt flag so higher-level code (e.g. server shutdown) can detect the interruption.
      Thread.currentThread().interrupt();
      throw new CheckInterruptedException(ex);
    }
  }

  /**
   * Throws exception.
   */
  public void throwException() {
    // Deliberate generic exception instead of GeneralException subclass.
    throw new IllegalArgumentException("This error message was caused deliberately (/api/checks/exception) and should not be visible externally.");
  }
}
