# Configuration specific to Spring.

spring:
  main:
    banner-mode: off # banner will screw with gcp logging
  mvc:
    problemdetails:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate # never use 'update' or 'create', Flyway takes care of it
    open-in-view: false # disable Open-In-View
  flyway:
    schemas: aux
    table: flyway_schema_history
  cloud:
    gcp: # disable gcp stuff locally, it will be enabled on gcp profile
      core:
        enabled: false
      logging:
        enabled: false

# Since it is portfolio project, it is fine to expose some Actuator endpoints.
management:
  endpoints:
    web:
      exposure: # ONLY expose these specific, safe endpoints
        include: "health,info,metrics,prometheus,mappings"
  info:
    env:
      enabled: true   # Allows the /actuator/info endpoint to show environment details

# Secrets are defined in GitHub (Repository Secrets).
security:
  jwt:
    secret: ${JWT_SECRET:qXqyG/cXonpbJY7zfChA/XoatblyieXumWmRg3mYjUc=} # Bytes encoded in BASE64. This is default in case JWT_SECRET is missing, we can use whatever locally.
    expiration: 360 # 6 hours, in minutes