# Configuration specific to UserLand project: scheduling.

app:
  scheduling: # General config.
    enabled: true # Explicitly enables all schedulers globally, checked in SchedulerConfig.
  scheduler: # Config specific to particular scheduler.
    user:
      cleanup:
        users:
          delay: 6h
          initial: 5m
        tokens:
          delay: 6h
          initial: 10m # to prevent user and token cleanup starting simultaneously
        jwt:
          delay: 6h
          initial: 15m