# Configuration specific to UserLand project: scheduling.

app:
  scheduling: # General config.
    enabled: true # Explicitly enables all schedulers globally, checked in SchedulerConfig.
  scheduler: # Config specific to particular scheduler.
    user:
      cleanup:
        users:
          pending:
            delay: 6h
            initial: 5m
          active: # only in portfolio mode
            delay: 24h
            initial: 1m
        tokens:
          delay: 6h
          initial: 10m
        jwt:
          delay: 6h
          initial: 15m