# Configuration specific to UserLand project: email.

spring:
  thymeleaf:
    prefix: "classpath:/templates/emails/"
  mail: # plain email provider config is here
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: 587
    username: ${EMAIL_USERNAME:pawel.papierkowski.portfolio@gmail.com}
    password: ${EMAIL_PASSWORD:APP_PASSWORD} # real App password should be in secrets provided by GitHub
    protocol: smtp
    default-encoding: UTF-8
    test-connection: true # If true, fail fast on boot if credentials are bad.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${EMAIL_HOST:smtp.gmail.com}
          # Prevent infinite hanging threads!
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

app:
  email:
    sender: ${EMAIL_SENDER:onboarding@resend.dev}
    response: ${EMAIL_RESPONSE:onboarding@resend.dev}
    providers:
      default: ${EMAIL_DEFAULT_PROVIDER:resend} # default provider
      resend:
        api-key: ${TEP_RESEND_APIKEY:} # API key used for TEP Resend