# Configuration specific to UserLand project: general.

app:
  main:
    www: https://pawel-papierkowski.github.io/frontend-userland- # does not exist yet
  user:
    pending:
      removal-delay: 48 # when to remove pending users since creation, in hours
    token:
      length: 32
      activation: # user account activation
        expires: 24 # in hours
      password: # user password reset
        expires: 30 # in minutes
      deletion: # user account deletion
        expires: 30 # in minutes