spring:
  thymeleaf:
    prefix: "classpath:/templates/emails/"
  mail: # plain email provider config is here
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: 587
    username: ${EMAIL_USERNAME:pawel.papierkowski.portfolio@gmail.com}
    password: ${EMAIL_PASSWORD:APP_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    test-connection: true # If true, fail fast on boot if credentials are bad.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${EMAIL_HOST:smtp.gmail.com}
          # Prevent infinite hanging threads!
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

app:
  email:
    sender: "pawel.papierkowski.portfolio@gmail.com"
    providers:
      default: 'plain' # default provider
      resend:
        api-key: ${TEP_RESEND_APIKEY:PLACEHOLDER_API_KEY} # API key used for TEP Resend