# Main configuration file.
spring:
  application:
    name: userland-backend
  config:
    import:
      - classpath:config/spring.yaml
      - classpath:config/logging.yaml
      - classpath:config/userland.yaml
