package org.portfolio.userland.features.check;

import org.junit.jupiter.api.Test;
import org.portfolio.userland.common.constants.EnAppBuild;
import org.portfolio.userland.common.constants.ValidConst;
import org.portfolio.userland.features.check.dto.CheckInfoResp;
import org.portfolio.userland.features.user.entities.EnUserHistoryWhat;
import org.portfolio.userland.features.user.entities.EnUserHistoryWho;
import org.portfolio.userland.features.user.entities.EnUserStatus;
import org.portfolio.userland.features.user.entities.User;
import org.portfolio.userland.system.auth.jwt.JwtService;
import org.portfolio.userland.system.config.service.ConfigConst;
import org.portfolio.userland.test.helpers.problemDetail.ProblemDetailBox;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.info.BuildProperties;
import org.springframework.http.HttpStatus;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.transaction.annotation.Transactional;

import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;

/**
 * Test check endpoints.
 * Note endpoints that require login/permissions have manually arranged user instead of <code>@WithMockCustomUser.</code>
 * This is deliberate - we are testing full flow here without mocking Spring's user detail.
 */
public class CheckApiTest extends BaseCheckTest {
  /** Real service to generate a valid token. */
  @Autowired
  private JwtService jwtService;

  /** System name. */
  @Value("${app.main.name}")
  protected String systemName;
  /** Build information of the application (generated by spring-boot-maven-plugin's build-info goal). */
  @Autowired
  private BuildProperties buildProperties;

  // //////////////////////////////////////////////////////////////////////////

  @Test
  void enterUnsecuredEndpoint() throws Exception {
    clock.setFixedTime("2026-04-10T10:00:00Z");
    // No arrange here.

    // Act: Perform the request using MockMvc.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/alive"))
        .andReturn();

    // Assert: API response should indicate success.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.NO_CONTENT.value());
    assertThat(mvcResult.getResponse().getContentAsString()).as("Response body should be empty").isEqualTo("");
  }

  @Test
  void enterSecuredEndpointWithValidToken() throws Exception {
    clock.setFixedTime("2026-04-10T10:00:00Z");

    // Arrange: Create a user, token and JWT entry in database, emulating user login.
    User user = userFactory.genRandUserLogged();
    userRepository.save(user);
    String token = userJwtRepository.findAll().getFirst().getToken();

    // Act: Perform the request using MockMvc.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/must-be-logged")
            .header("Authorization", "Bearer " + token))
        .andReturn();

    // Assert: API response should indicate success.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.NO_CONTENT.value());
    assertThat(mvcResult.getResponse().getContentAsString()).as("Response body should be empty").isEqualTo("");
  }

  @Test
  void enterAdminEndpointWithValidToken() throws Exception {
    clock.setFixedTime("2026-04-10T10:00:00Z");

    // Arrange: Create a user, token and JWT entry in database, emulating user login.
    User user = userFactory.genRandUserLogged(Map.of("role", "admin"));
    userRepository.save(user);
    String token = userJwtRepository.findAll().getFirst().getToken();

    // Act: Perform the request using MockMvc.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/must-be-admin")
            .header("Authorization", "Bearer " + token))
        .andReturn();

    // Assert: API response should indicate success.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.NO_CONTENT.value());
    assertThat(mvcResult.getResponse().getContentAsString()).as("Response body should be empty").isEqualTo("");
  }

  //

  @Test
  @Transactional
  void enterLockdownSecuredEndpointAsAdmin() throws Exception {
    clock.setFixedTime("2026-04-10T10:00:00Z");

    // Arrange: Create an admin user, token and JWT entry in database, emulating user login.
    User user = userFactory.genRandUserLogged(Map.of("role", "admin"));
    userRepository.save(user);
    String token = userJwtRepository.findAll().getFirst().getToken();

    // Arrange: Lock down system.
    configRepository.updateValueByName(ConfigConst.USER_LOCKDOWN, ConfigConst.TRUE);

    // Act: Perform the request using MockMvc.
    // Normally you do not need any permission, just being logged in. But during lockdown only admins can call ANY endpoint.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/must-be-logged")
            .header("Authorization", "Bearer " + token))
        .andReturn();

    // Assert: API response should indicate success.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.NO_CONTENT.value());
    assertThat(mvcResult.getResponse().getContentAsString()).as("Response body should be empty").isEqualTo("");
  }

  //

  @Test
  void lockPretendWorkEndpoint() throws Exception {
    // Test that locking works. We want to call endpoint twice: first time should succeed, second time should be refused
    // since pretend work endpoint is still busy.

    // Arrange: Create an admin user, token and JWT entry in database, emulating user login.
    User user = userFactory.genRandUserLogged(Map.of("role", "admin"));
    userRepository.save(user);
    String token = userJwtRepository.findAll().getFirst().getToken();

    // Fire the first request asynchronously in a dedicated thread. Unlike CompletableFuture.cancel(), shutdownNow()
    // below truly interrupts the thread, which breaks the 30-second sleep inside the endpoint and lets LockService
    // release the lock in its finally block.
    ExecutorService executor = Executors.newSingleThreadExecutor();
    try {
      executor.submit(() -> mockMvc.perform(get("/api/checks/pretendWork")
              .header("Authorization", "Bearer " + token))
          .andReturn());

      // Wait until the first request has actually reached the controller and acquired the ShedLock. We poll the
      // aux.shedlock table instead of guessing with a sleep - this is deterministic even on slow CI machines.
      awaitPretendWorkLock(true);

      // Fire the second request on the main test thread and assert it was rejected with 423 LOCKED.
      MvcResult secondResult = mockMvc.perform(get("/api/checks/pretendWork")
              .header("Authorization", "Bearer " + token))
          .andReturn();
      assertThat(secondResult.getResponse().getStatus())
          .as("Second request should be blocked by ShedLock").isEqualTo(HttpStatus.LOCKED.value());
    } finally {
      // Interrupt the 30-second work so the test does not have to wait for it (and so the lock gets released).
      executor.shutdownNow();
    }

    // Wait until the lock is really released (interrupt processed, finally-unlock done), so no state leaks into
    // subsequent tests.
    awaitPretendWorkLock(false);
  }

  /**
   * Waits (with timeout) until the ShedLock row of the pretend work endpoint reaches the required state.
   * <p>Note: ShedLock is configured with {@code usingDbTime()}, so lock expiry must be evaluated against database
   * time too - doing it JVM-side would break when application and database use different timezones.</p>
   * @param expectLocked True to wait until the lock is held, false to wait until it is released.
   */
  private void awaitPretendWorkLock(boolean expectLocked) {
    await().atMost(Duration.ofSeconds(10)).untilAsserted(() -> {
      // Native query bypasses the persistence context - we need current database state, not cached entities.
      List<?> locks = entityManager.createNativeQuery(
              "SELECT name FROM aux.shedlock WHERE name = :name AND lock_until > CURRENT_TIMESTAMP AT TIME ZONE 'UTC'")
          .setParameter("name", "CheckLock_pretendWork")
          .getResultList();
      assertThat(!locks.isEmpty())
          .as("Pretend work lock should be %s", expectLocked ? "held" : "released")
          .isEqualTo(expectLocked);
    });
  }

  @Test
  void enterExceptionEndpoint() throws Exception {
    // No arrange here.

    // Act: Perform the request using MockMvc.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/exception"))
        .andReturn();

    // Assert: API response should indicate failure.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR.value());
    // Assert: Correct problem detail is present.
    ProblemDetailBox expectedPdb = new ProblemDetailBox(
        HttpStatus.INTERNAL_SERVER_ERROR.value(),
        "Internal Server Error",
        "An unexpected error occurred while processing your request.",
        "/api/checks/exception",
        "https://api.general.org/errors/internal",
        Map.of()
    );
    problemDetailService.assertPd(mvcResult, expectedPdb);
  }

  // //////////////////////////////////////////////////////////////////////////

  @Test
  void errWithoutToken() throws Exception {
    // Try to call endpoint that requires being logged in, but we are not logged in.
    clock.setFixedTime("2026-04-10T10:00:00Z");
    // No arrange here.

    // Act: This endpoint expects token, but there is no token. So Spring rejects it (throwing 401 Unauthorized).
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/must-be-logged"))
        .andReturn();

    // Assert: API response should indicate failure.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.UNAUTHORIZED.value());
    // Assert: Correct problem detail is present.
    problemDetailService.assertPdUnauthorized(mvcResult, "/api/checks/must-be-logged");
  }

  @Test
  void errMalformedToken() throws Exception {
    clock.setFixedTime("2026-04-10T10:00:00Z");
    // No arrange here.

    // Act: This endpoint expects token, but token is malformed. So Spring rejects it (throwing 401 Unauthorized).
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/must-be-logged")
            .header("Authorization", "Bearer MALFORMED_TOKEN"))
        .andReturn();

    // Assert: API response should indicate failure.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.UNAUTHORIZED.value());
    // Assert: Check the header required by RFC 6750.
    String authHeader = mvcResult.getResponse().getHeader("WWW-Authenticate");
    assertThat(authHeader)
        .as("WWW-Authenticate header is missing or incorrect")
        .isEqualTo("Bearer error=\"invalid_token\"");
    // Assert: Correct problem detail is present.
    ProblemDetailBox expectedPdb = new ProblemDetailBox(
        HttpStatus.UNAUTHORIZED.value(),
        "Unauthorized",
        "Bearer token is expired, invalid or malformed and cannot be used.",
        "/api/checks/must-be-logged",
        "https://api.userland.org/errors/user/malformedToken",
        Map.of("errCode", "jwt_0001")
    );
    problemDetailService.assertPd(mvcResult, expectedPdb);
  }

  @Test
  void errNoJwtInDatabase() throws Exception {
    clock.setFixedTime("2026-04-10T10:00:00Z");

    // Arrange: Create a user and token. Note UserJwt entry is not added. This will emulate state when we logged in
    // and then logged out. Token is still valid, but we know it is revoked because it is missing from UserJwt table.
    User user = userFactory.genRandUser(EnUserStatus.ACTIVE);
    userHistoryFactory.genHistoryEvent(user, EnUserHistoryWho.USER, EnUserHistoryWhat.LOGIN, "");
    String token = jwtService.generateToken(user);
    userHistoryFactory.genHistoryEvent(user, EnUserHistoryWho.USER, EnUserHistoryWhat.LOGOUT, "");
    userRepository.save(user);

    // Act: Perform the request using MockMvc.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/must-be-logged")
            .header("Authorization", "Bearer " + token))
        .andReturn();

    // Assert: API response should indicate failure.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.UNAUTHORIZED.value());
    // Assert: Correct problem detail is present.
    problemDetailService.assertPdUnauthorized(mvcResult, "/api/checks/must-be-logged");
  }

  @Test
  void errPendingUser() throws Exception {
    clock.setFixedTime("2026-04-10T10:00:00Z");

    // Arrange: Create a real user.
    User user = userRepository.save(userFactory.genRandUser(EnUserStatus.ACTIVE));
    // Arrange: Create a real token.
    String token = jwtService.generateToken(user);

    // Arrange: Now set user back to PENDING.
    clock.setFixedTime("2026-04-10T11:00:00Z");
    user.setStatus(EnUserStatus.PENDING);
    userRepository.save(user);

    // Act: Perform the request using MockMvc.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/must-be-logged")
            .header("Authorization", "Bearer " + token))
        .andReturn();

    // Assert: API response should indicate failure.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.UNAUTHORIZED.value());
    // Assert: Correct problem detail is present.
    problemDetailService.assertPdUnauthorized(mvcResult, "/api/checks/must-be-logged");
  }

  @Test
  void errLockedUser() throws Exception {
    clock.setFixedTime("2026-04-10T10:00:00Z");

    // Arrange: Create a real user.
    User user = userRepository.save(userFactory.genRandUser(EnUserStatus.ACTIVE));
    // Arrange: Create a real token.
    String token = jwtService.generateToken(user);

    // Arrange: Now lock user.
    clock.setFixedTime("2026-04-10T11:00:00Z");
    user.setLocked(true);
    userRepository.save(user);

    // Act: Perform the request using MockMvc.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/must-be-logged")
            .header("Authorization", "Bearer " + token))
        .andReturn();

    // Assert: API response should indicate failure.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.UNAUTHORIZED.value());
    // Assert: Correct problem detail is present.
    problemDetailService.assertPdUnauthorized(mvcResult, "/api/checks/must-be-logged");
  }

  @Test
  void errNoAdmin() throws Exception {
    // Try to call endpoint that requires admin permissions while not having these permissions.
    clock.setFixedTime("2026-04-10T10:00:00Z");

    // Arrange: Create a user, token and JWT entry in database, emulating user login. No admin permissions.
    User user = userFactory.genRandUserLogged();
    userRepository.save(user);
    String token = userJwtRepository.findAll().getFirst().getToken();

    // Act: Perform the request using MockMvc.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/must-be-admin")
            .header("Authorization", "Bearer " + token))
        .andReturn();

    // Assert: API response should indicate failure.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.FORBIDDEN.value());
    // Assert: Correct problem detail is present.
    problemDetailService.assertPdForbidden(mvcResult, "/api/checks/must-be-admin");
  }

  //

  @Test
  void errLockdownUnsecuredEndpoint() throws Exception {
    // Try to access unsecured endpoint during lockdown.
    clock.setFixedTime("2026-04-10T10:00:00Z");

    // Arrange: Lock down system.
    transactionTemplate.execute(_ -> {
      configRepository.updateValueByName(ConfigConst.USER_LOCKDOWN, ConfigConst.TRUE);
      return null;
    });

    // Act: Perform the request using MockMvc.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/alive"))
        .andReturn();

    // Assert: API response should indicate failure.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.CONFLICT.value());
    ProblemDetailBox expectedPdb = new ProblemDetailBox(
        HttpStatus.CONFLICT.value(),
        "System lockdown is in effect.",
        "System lockdown is in effect.",
        "/api/checks/alive",
        "https://api.userland.org/errors/system/lockdown",
        Map.of("errCode", "lock_0001")
    );
    problemDetailService.assertPd(mvcResult, expectedPdb);
  }

  @Test
  void errLockdownSecuredEndpoint() throws Exception {
    // Try to access secured endpoint during lockdown.
    clock.setFixedTime("2026-04-10T10:00:00Z");

    // Arrange: Create a user, token and JWT entry in database, emulating user login.
    User user = userFactory.genRandUserLogged();
    userRepository.save(user);
    String token = userJwtRepository.findAll().getFirst().getToken();

    // Arrange: Lock down system.
    transactionTemplate.execute(_ -> {
      configRepository.updateValueByName(ConfigConst.USER_LOCKDOWN, ConfigConst.TRUE);
      return null;
    });

    // Act: Perform the request using MockMvc.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/must-be-logged")
            .header("Authorization", "Bearer " + token))
        .andReturn();

    // Assert: API response should indicate failure.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.CONFLICT.value());
    ProblemDetailBox expectedPdb = new ProblemDetailBox(
        HttpStatus.CONFLICT.value(),
        "System lockdown is in effect.",
        "User with email '"+user.getEmail()+"' cannot access endpoint due to lockdown.",
        "/api/checks/must-be-logged",
        "https://api.userland.org/errors/user/lockdown",
        Map.of("errCode", "lock_0002")
    );
    problemDetailService.assertPd(mvcResult, expectedPdb);
  }

  // //////////////////////////////////////////////////////////////////////////

  @Test
  void requestInfo() throws Exception {
    // Call info endpoint.
    clock.setFixedTime("2026-04-10T10:00:00Z");

    // Arrange: Create a user, token and JWT entry in database, emulating user login.
    User user = userFactory.genRandUserLogged(Map.of("role", "admin"));
    userRepository.save(user);
    String token = userJwtRepository.findAll().getFirst().getToken();

    // Act: Perform the request using MockMvc.
    MvcResult mvcResult = mockMvc.perform(get("/api/checks/info")
            .header("Authorization", "Bearer " + token))
        .andReturn();

    // Assert: API response should indicate success.
    assertThat(mvcResult.getResponse().getStatus()).as("HTTP status is wrong").isEqualTo(HttpStatus.OK.value());
    // Assert: Endpoint response. Note we do not check bootAt (as it changes all the time).
    CheckInfoResp actualResp = objectMapper.readValue(mvcResult.getResponse().getContentAsString(), CheckInfoResp.class);
    CheckInfoResp expectedResp = CheckInfoResp.builder()
        .name(systemName)
        .nowAt(clockService.getNowUTC())
        .bootAt(actualResp.bootAt()) // skip
        .version(buildProperties.getVersion())
        .profile(EnAppBuild.TEST)
        .build();
    assertThat(actualResp).as("System info is invalid").isEqualTo(expectedResp);
    assertThat(actualResp.version()).as("Version is invalid").matches(ValidConst.VERSION_REGEXPR); // ensure build-info version is correctly resolved
  }
}
