# What this workflow does:
# - Check out repo to GitHub Ubuntu server.
# - Set up Java 25 Temurin.
# - Compile docker image on GitHub.
# - Upload image as artifact to Google Cloud. It will be automatically run once deployed.
name: Deploy Docker Image to Cloud

# Required variables:
# - GCP_SERVICE_ACC: Name of service account for GCP project.
# - GCP_GAR_LOCATION: Data center region.
# - GCP_REPOSITORY: GCP Artifact Registry Repository.
# - GCP_DASHBOARD_NAME: Name that backend will have in the Google Cloud Run dashboard.
# Required secrets:
# - GCP_PROJECT_ID: Identificator of project on Google Cloud.
# - GCP_WORKLOAD_IDENTITY_PROVIDER: For WIP login on Google Cloud.
# See README.md for description of other needed variables/secrets.

on:
  # This allows you to click a "Run workflow" button manually in GitHub
  # without automatic run every time you push code on GitHub.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # This is required for requesting the OIDC JWT.
    steps:
      # Clone repo to temporary Ubuntu build server provided by GitHub.
      - name: Checkout Code
        uses: actions/checkout@v6

      # Install Java 25 JDK (Temurin distribution).
      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven' # save downloaded dependencies for next time

      # Authenticate to Google Cloud using WIF. You can test it separately (test-gcp-auth.yml).
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ vars.GCP_SERVICE_ACC }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      # Note: currently we should be logged into Google Cloud.
      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker ${{ vars.GCP_GAR_LOCATION }}-docker.pkg.dev --quiet

      # Core of the pipeline!
      # Compiles the app directly into a Docker image and pushes it to Google Artifact Registry.
      # chmod +x mvnw grants execution permissions to the Maven wrapper.
      # The -D...publish=true flag tells Maven to immediately upload that finished Docker image
      # to your Google Artifact Registry using the unique commit hash ${{ github.sha }} as the version tag.
      - name: Build and Push Docker Image
        run: |
          chmod +x mvnw
          
          IMAGE_URL="${{ vars.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.GCP_REPOSITORY }}/${{ vars.GCP_DASHBOARD_NAME }}:${{ github.sha }}"
          
          ./mvnw spring-boot:build-image \
            -Dspring-boot.build-image.imageName=$IMAGE_URL \
            -Dspring-boot.build-image.publish=true

      # Launch a new container using the image that was just uploaded. Deployment is heavily tuned to squeeze every drop
      # of memory out of that container.
      # --allow-unauthenticated means the website is public and anyone on the internet can hit your API endpoints.
      # --memory=512Mi explicitly limits the container RAM.
      # env_vars:
      #   SPRING_PROFILES_ACTIVE: Activates gcp profile in Spring.
      #   SPRING_DATASOURCE_*: Injects the database credentials into the Cloud Run container.
      #   BPL_JVM_THREAD_COUNT: Paketo has 250 by default, cut it down.
      #   BPL_JVM_HEAD_ROOM: Tells Paketo how much % of container memory should be reserved for non-Java things like OS.
      #   BPL_JAVA_NMT_ENABLED: Disable Paketo's memory tracking. Mainly for clean logs.
      #   BPL_SPRING_CLOUD_BINDINGS_DISABLED: Disable Paketo's scanner for Kubernet stuff. Not needed, as we do not use Kubernet.
      #   JAVA_TOOL_OPTIONS: Use JVM arguments that will make JVM behave better in constrained environment.
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: ${{ vars.GCP_DASHBOARD_NAME }}
          region: ${{ vars.GCP_GAR_LOCATION }}
          image: ${{ vars.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.GCP_REPOSITORY }}/${{ vars.GCP_DASHBOARD_NAME }}:${{ github.sha }}
          flags: '--allow-unauthenticated --memory=1Gi --cpu-boost --timeout=300'
          env_vars: |-
            SPRING_PROFILES_ACTIVE=gcp
            SPRING_DATASOURCE_URL=${{ secrets.DB_URL }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}
            BPL_JVM_THREAD_COUNT=50
            BPL_JVM_HEAD_ROOM=25
            BPL_JAVA_NMT_ENABLED=false
            BPL_SPRING_CLOUD_BINDINGS_DISABLED=true
            JAVA_TOOL_OPTIONS=-XX:+UseSerialGC -Xss512k -XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=128M
            BUILD=${{ vars.BUILD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EMAIL_DEFAULT_PROVIDER=${{ vars.EMAIL_DEFAULT_PROVIDER }}
            EMAIL_SENDER=${{ vars.EMAIL_SENDER }}
            EMAIL_RESPONSE=${{ vars.EMAIL_RESPONSE }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            TEP_RESEND_APIKEY=${{ secrets.TEP_RESEND_APIKEY }}
